### ISSUE TITLE
If nimterop is installed in a non-default location (not in ~/.nimble), cImport compilation fails with inability to find nimterop/plugin

### ISSUE THREAD

**Issue by kaushalmodi** [nimterop/nimterop#151]
Ref: https://gitter.im/nim-lang/Nim?at=5dc05828a4541815c8a34fd0

**Summary**: If the user does not have a `~/.nimble` directory and they have the Nimble packages installed at `/my/custom/.nimble`, nimterop will fail compilation at `cImport` for being unable to find the `nimterop/plugin`, even if the compilation is done using `nim c --NimblePath=/my/custom/.nimble/pkgs`.

I have obfuscated the dir names as this compile error is while running into this error on some work stuff:

```
nim --NimblePath:/my/custom/share/nimble/pkgs cpp --styleCheck:off -o:/tmp/kmodi/foo_wrapper0 foo_wrapper0.nim > foo_types.nim
Hint: used config file '/my/custom/apps/nim/1.0.2/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
Hint: used config file '/prj/dir/config.nims' [Conf]
stack trace: (most recent call last)
/my/custom/share/nimble/pkgs/nimterop-0.3.3/nimterop/cimport.nim(593, 22) cImport
/my/custom/share/nimble/pkgs/nimterop-0.3.3/nimterop/cimport.nim(170, 11) getToast
/my/custom/apps/nim/1.0.2/lib/system/assertions.nim(27, 20) failedAssertImpl
/my/custom/apps/nim/1.0.2/lib/system/assertions.nim(20, 11) raiseAssert
/my/custom/apps/nim/1.0.2/lib/system/fatal.nim(39, 5) sysFatal
/prj/dir/foo_wrapper0.nim(85, 8) template/generic instantiation of `cImport` from here
/my/custom/apps/nim/1.0.2/lib/system/fatal.nim(39, 5) Error: unhandled exception: /my/custom/share/nimble/pkgs/nimterop-0.3.3/nimterop/cimport.nim(170, 12) `ret == 0`

toast.nim                toast
cligen.nim               cligenDoNotCollideWithGlobalVar
cligen.nim               dispatchmain
toast.nim                main
getters.nim              loadPlugin
build.nim                execAction
assertions.nim           failedAssertImpl
assertions.nim           raiseAssert
fatal.nim                sysFatal
Error: unhandled exception: build.nim(57, 16) `false` Command failed: (1, false)
cmd: /my/custom/apps/nim/1.0.2/bin/nim c --app:lib /tmp/kmodi/.cache/nim/nimterop/cPlugins/nimterop_1408812938.nim
result:
Hint: used config file '/my/custom/apps/nim/1.0.2/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/.config/nim/config.nims' [Conf]
/tmp/kmodi/.cache/nim/nimterop/cPlugins/nimterop_1408812938.nim(1, 24) Error: cannot open file: nimterop/plugin
 [AssertionError] [AssertionError]
make[1]: *** [Makefile:18: update] Error 1
```

Above, I am running:

```
nim --NimblePath:/my/custom/share/nimble/pkgs cpp --styleCheck:off -o:/tmp/kmodi/foo_wrapper0 foo_wrapper0.nim > foo_types.nim
```

The fix/workaround was to pass the custom nimble path via the env var NIMBLE_DIR too:

```
NIMBLE_DIR=/my/custom/share/nimble/pkgs nim --NimblePath:/my/custom/share/nimble/pkgs cpp --styleCheck:off -o:/tmp/kmodi/foo_wrapper0 foo_wrapper0.nim > foo_types.nim
```

**Comment by kaushalmodi** [comment]
Note that this issue is a regression in one of the nimterop releases. When I was using the latest HEAD at some point when there was no tagged release of nimterop, I did not need to set the NIMBLE_DIR env var this way. But now I do.

May be in https://github.com/genotrance/nimterop/blob/36726e2442f9e78afda7906b1765e02432ff9489/nimterop/getters.nim#L472, you pass a `--path` with the value derived from [`currentSourcePath`][1]?

[1]: https://nim-lang.github.io/Nim/system.html#currentSourcePath.t

**Comment by genotrance** [comment]
This is similar to https://github.com/nimterop/nimterop/issues/153 - since Nimterop does not know what flags Nim was invoked with, the child Nim process used to compile plugins does not know any better.

$NIMBLE_DIR propagates and so does the usage of nim.cfg with the right info. At this time, I do not know of a way to get the command line flags at compile time so that I can propagate them.

**Comment by genotrance** [comment]
This is fixed in the `nimcfg` branch - requesting some testing before I merge. Thanks in advance.

**Comment by genotrance** [comment]
cc @disruptek

Note this only works on Nim v1.2.0+ since that's the release that adds `std/compilesettings` and additional details in `nim dump`. Before that release, it is not fool proof since we only get `--path` entry details but no `nimblePaths` nor `lazyPaths` so not all cases will be covered.

**Comment by kaushalmodi** [comment]
@genotrance I tried out the branch, but I still see that error, though now failing because of a different AssertionError: https://gitter.im/nimterop/Lobby?at=5ea86388d898fe7a375231b6
