### ISSUE TITLE
Identifiers in expressions might not get sanitized in Enums, array sizes

### ISSUE THREAD

**Issue by genotrance** [nimterop/nimterop#57]
```c
struct foo { int foo[8+1]; };
struct foo { int foo[__MAGICNUM+1]; };
```

First will work, second too but __MAGICNUM won't get cleaned up.

**Comment by genotrance** [comment]
Fixed in #head.

**Comment by zacharycarter** [comment]
Still appears to be an issue for enums.

```
import os, nimterop/[build, cimport]

const
    baseDir = currentSourcePath.parentDir() / "lib" / "sokol"

static:
  cDebug()

cDefine("SOKOL_IMPL")
cDefine("SOKOL_D3D11")

cPlugin:
  import strutils

  proc onSymbol*(sym: var Symbol) {.exportc, dynlib.} =
    sym.name = sym.name.strip(chars = {'_'})

cImport(baseDir / "sokol_gfx.h")
```

`SG_SLOT_MASK* = ((1 shl _SG_SLOT_SHIFT)-1).Enum_sokol_gfxh2`

`C:\Users\carte\AppData\Local\Temp\nimterop_1978424579.nim(609, 28) Error: invalid token: _ (\95)`
